// Synthetic seed data for the public demo deployment.
// Generated from live TMDB API — all poster_path and backdrop_path values are
// verified. Real TMDB ids so posters, cast, providers load live from the CDN.

import type { ListRow, TitleRow } from "@/lib/types";

function ts(daysAgo: number): string {
  const base = Date.UTC(2026, 3, 1);
  return new Date(base - daysAgo * 86400_000).toISOString();
}

function title(partial: Partial<TitleRow> & Pick<TitleRow, "id" | "tmdb_id" | "media_type" | "title" | "status">): TitleRow {
  return {
    original_title: partial.title,
    overview: null,
    poster_path: null,
    backdrop_path: null,
    release_date: null,
    runtime: null,
    genres: null,
    rating: null,
    review: null,
    favorite: false,
    added_at: ts(0),
    watched_at: null,
    tmdb_rating: null,
    tmdb_vote_count: null,
    imdb_id: null,
    imdb_rating: null,
    imdb_votes: null,
    rt_score: null,
    metacritic_score: null,
    ratings_fetched_at: null,
    ...partial,
  };
}

export const DEMO_TITLES: TitleRow[] = [

  // ── Want (15) ──────────────────────────────────────────────────────
  title({
    id: "demo-want-1",
    tmdb_id: 693134,
    media_type: "movie",
    title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "/eZ239CUp1d6OryZEBPnO2n87gMG.jpg",
    release_date: "2024-02-27",
    runtime: 167,
    genres: [{"id":878,"name":"Science Fiction"},{"id":12,"name":"Adventure"}],
    status: "want",
    added_at: ts(1),
    watched_at: null,
  }),
  title({
    id: "demo-want-2",
    tmdb_id: 95396,
    media_type: "tv",
    title: "Severance",
    overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    poster_path: "/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg",
    backdrop_path: "/ixgFmf1X59PUZam2qbAfskx2gQr.jpg",
    release_date: "2022-02-17",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":9648,"name":"Mystery"},{"id":10765,"name":"Sci-Fi & Fantasy"}],
    status: "want",
    added_at: ts(2),
    watched_at: null,
  }),
  title({
    id: "demo-want-3",
    tmdb_id: 933260,
    media_type: "movie",
    title: "The Substance",
    overview: "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    backdrop_path: "/8ODNt5olCeIqBYTP3GgXEQYTfeX.jpg",
    release_date: "2024-09-07",
    runtime: 141,
    genres: [{"id":27,"name":"Horror"},{"id":878,"name":"Science Fiction"},{"id":18,"name":"Drama"}],
    status: "want",
    added_at: ts(3),
    watched_at: null,
  }),
  title({
    id: "demo-want-4",
    tmdb_id: 126308,
    media_type: "tv",
    title: "Shōgun",
    overview: "In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.",
    poster_path: "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
    backdrop_path: "/bwSmgmd90hCWwqOKQYTEraeOZhJ.jpg",
    release_date: "2024-02-27",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":10768,"name":"War & Politics"}],
    status: "want",
    added_at: ts(4),
    watched_at: null,
  }),
  title({
    id: "demo-want-5",
    tmdb_id: 100088,
    media_type: "tv",
    title: "The Last of Us",
    overview: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
    backdrop_path: "/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg",
    release_date: "2023-01-15",
    runtime: null,
    genres: [{"id":18,"name":"Drama"}],
    status: "want",
    added_at: ts(5),
    watched_at: null,
  }),
  title({
    id: "demo-want-6",
    tmdb_id: 666277,
    media_type: "movie",
    title: "Past Lives",
    overview: "After decades apart, childhood friends Nora and Hae Sung are reunited in New York for one fateful weekend as they confront notions of destiny, love, and the choices that make a life.",
    poster_path: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    backdrop_path: "/7HR38hMBl23lf38MAN63y4pKsHz.jpg",
    release_date: "2023-06-02",
    runtime: 106,
    genres: [{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],
    status: "want",
    added_at: ts(6),
    watched_at: null,
  }),
  title({
    id: "demo-want-7",
    tmdb_id: 106379,
    media_type: "tv",
    title: "Fallout",
    overview: "The story of haves and have-nots in a world in which there's almost nothing left to have. 200 years after the apocalypse, the gentle denizens of luxury fallout shelters are forced to return to the irradiated hellscape their ancestors left behind — and are shocked to discover an incredibly complex, gleefully weird, and highly violent universe waiting for them.",
    poster_path: "/c15BtJxCXMrISLVmysdsnZUPQft.jpg",
    backdrop_path: "/cIgHBLTMbcIkS0yvIrUUVVKLdOz.jpg",
    release_date: "2024-04-10",
    runtime: null,
    genres: [{"id":10759,"name":"Action & Adventure"},{"id":10765,"name":"Sci-Fi & Fantasy"}],
    status: "want",
    added_at: ts(7),
    watched_at: null,
  }),
  title({
    id: "demo-want-8",
    tmdb_id: 792307,
    media_type: "movie",
    title: "Poor Things",
    overview: "Brought back to life by an unorthodox scientist, a young woman runs off with a lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdrop_path: "/zh6IdheEYinU4TPtorWsjx6qPQE.jpg",
    release_date: "2023-12-07",
    runtime: 141,
    genres: [{"id":878,"name":"Science Fiction"},{"id":10749,"name":"Romance"},{"id":35,"name":"Comedy"}],
    status: "want",
    added_at: ts(8),
    watched_at: null,
  }),
  title({
    id: "demo-want-9",
    tmdb_id: 46648,
    media_type: "tv",
    title: "True Detective",
    overview: "An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.",
    poster_path: "/zYqVTiHK5ZajYcNzAW7qWte5NWS.jpg",
    backdrop_path: "/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg",
    release_date: "2014-01-12",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":9648,"name":"Mystery"}],
    status: "want",
    added_at: ts(9),
    watched_at: null,
  }),
  title({
    id: "demo-want-10",
    tmdb_id: 872585,
    media_type: "movie",
    title: "Oppenheimer",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg",
    release_date: "2023-07-19",
    runtime: 181,
    genres: [{"id":18,"name":"Drama"},{"id":36,"name":"History"}],
    status: "want",
    added_at: ts(10),
    watched_at: null,
  }),
  title({
    id: "demo-want-11",
    tmdb_id: 974576,
    media_type: "movie",
    title: "Conclave",
    overview: "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
    poster_path: "/vYEyxF1UT779RiEalpMjUT6kfdf.jpg",
    backdrop_path: "/eZzNdjNDvaSoyywy9ICg2UmFwul.jpg",
    release_date: "2024-10-25",
    runtime: 120,
    genres: [{"id":18,"name":"Drama"},{"id":53,"name":"Thriller"}],
    status: "want",
    added_at: ts(11),
    watched_at: null,
  }),
  title({
    id: "demo-want-12",
    tmdb_id: 238,
    media_type: "movie",
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop_path: "/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg",
    release_date: "1972-03-14",
    runtime: 175,
    genres: [{"id":18,"name":"Drama"},{"id":80,"name":"Crime"}],
    status: "want",
    added_at: ts(12),
    watched_at: null,
  }),
  title({
    id: "demo-want-13",
    tmdb_id: 111803,
    media_type: "tv",
    title: "The White Lotus",
    overview: "Follow the exploits of various guests and employees at an exclusive tropical resort over the span of a week as with each passing day, a darker complexity emerges in these picture-perfect travelers, the hotel’s cheerful employees and the idyllic locale itself.",
    poster_path: "/gbSaK9v1CbcYH1ISgbM7XObD2dW.jpg",
    backdrop_path: "/rCTLaPwuApDx8vLGjYZ9pRl7zRB.jpg",
    release_date: "2021-07-11",
    runtime: null,
    genres: [{"id":35,"name":"Comedy"},{"id":18,"name":"Drama"},{"id":9648,"name":"Mystery"}],
    status: "want",
    added_at: ts(13),
    watched_at: null,
  }),
  title({
    id: "demo-want-14",
    tmdb_id: 82856,
    media_type: "tv",
    title: "The Mandalorian",
    overview: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdrop_path: "/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg",
    release_date: "2019-11-12",
    runtime: null,
    genres: [{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":10759,"name":"Action & Adventure"}],
    status: "want",
    added_at: ts(14),
    watched_at: null,
  }),
  title({
    id: "demo-want-15",
    tmdb_id: 95480,
    media_type: "tv",
    title: "Slow Horses",
    overview: "Follow a dysfunctional team of MI5 agents—and their obnoxious boss, the notorious Jackson Lamb—as they navigate the espionage world's smoke and mirrors to defend England from sinister forces.",
    poster_path: "/dnpatlJrEPiDSn5fzgzvxtiSnMo.jpg",
    backdrop_path: "/bDfboQUb45Cv9MYyVBDZw8M8xSM.jpg",
    release_date: "2022-04-01",
    runtime: null,
    genres: [{"id":80,"name":"Crime"},{"id":18,"name":"Drama"},{"id":35,"name":"Comedy"}],
    status: "want",
    added_at: ts(15),
    watched_at: null,
  }),

  // ── Watching (7) ──────────────────────────────────────────────
  title({
    id: "demo-watching-1",
    tmdb_id: 76331,
    media_type: "tv",
    title: "Succession",
    overview: "Follow the lives of the Roy family as they contemplate their future once their aging father begins to step back from the media and entertainment conglomerate they control.",
    poster_path: "/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    backdrop_path: "/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg",
    release_date: "2018-06-03",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":35,"name":"Comedy"}],
    status: "watching",
    added_at: ts(16),
    watched_at: null,
  }),
  title({
    id: "demo-watching-2",
    tmdb_id: 94605,
    media_type: "tv",
    title: "Arcane",
    overview: "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
    backdrop_path: "/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg",
    release_date: "2021-11-06",
    runtime: null,
    genres: [{"id":16,"name":"Animation"},{"id":10759,"name":"Action & Adventure"},{"id":10765,"name":"Sci-Fi & Fantasy"}],
    status: "watching",
    added_at: ts(17),
    watched_at: null,
  }),
  title({
    id: "demo-watching-3",
    tmdb_id: 60059,
    media_type: "tv",
    title: "Better Call Saul",
    overview: "Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer\".",
    poster_path: "/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    backdrop_path: "/t15KHp3iNfHVQBNIaqUGW12xQA4.jpg",
    release_date: "2015-02-08",
    runtime: null,
    genres: [{"id":80,"name":"Crime"},{"id":18,"name":"Drama"}],
    status: "watching",
    added_at: ts(18),
    watched_at: null,
  }),
  title({
    id: "demo-watching-4",
    tmdb_id: 83867,
    media_type: "tv",
    title: "Andor",
    overview: "In an era filled with danger, deception and intrigue, Cassian Andor will discover the difference he can make in the struggle against the tyrannical Galactic Empire. He embarks on a path that is destined to turn him into a rebel hero.",
    poster_path: "/khZqmwHQicTYoS7Flreb9EddFZC.jpg",
    backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
    release_date: "2022-09-21",
    runtime: null,
    genres: [{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":10759,"name":"Action & Adventure"},{"id":18,"name":"Drama"}],
    status: "watching",
    added_at: ts(19),
    watched_at: null,
  }),
  title({
    id: "demo-watching-5",
    tmdb_id: 87108,
    media_type: "tv",
    title: "Chernobyl",
    overview: "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    backdrop_path: "/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg",
    release_date: "2019-05-06",
    runtime: null,
    genres: [{"id":18,"name":"Drama"}],
    status: "watching",
    added_at: ts(20),
    watched_at: null,
  }),
  title({
    id: "demo-watching-6",
    tmdb_id: 1429,
    media_type: "tv",
    title: "Attack on Titan",
    overview: "100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!",
    poster_path: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
    release_date: "2013-04-07",
    runtime: null,
    genres: [{"id":16,"name":"Animation"},{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":10759,"name":"Action & Adventure"}],
    status: "watching",
    added_at: ts(21),
    watched_at: null,
  }),
  title({
    id: "demo-watching-7",
    tmdb_id: 154385,
    media_type: "tv",
    title: "BEEF",
    overview: "A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.",
    poster_path: "/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg",
    backdrop_path: "/2VHbof9yaNhovEnaancBkXEULCT.jpg",
    release_date: "2023-04-06",
    runtime: null,
    genres: [{"id":35,"name":"Comedy"},{"id":18,"name":"Drama"}],
    status: "watching",
    added_at: ts(22),
    watched_at: null,
  }),

  // ── Watched (16) ──────────────────────────────────────────────
  title({
    id: "demo-watched-1",
    tmdb_id: 545611,
    media_type: "movie",
    title: "Everything Everywhere All at Once",
    overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    poster_path: "/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    backdrop_path: "/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
    release_date: "2022-03-24",
    runtime: 140,
    genres: [{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":878,"name":"Science Fiction"}],
    status: "watched",
    rating: 3,
    review: "Beautifully unhinged. Rarely does a film earn this much chaos.",
    favorite: true,
    added_at: ts(23),
    watched_at: ts(23),
  }),
  title({
    id: "demo-watched-2",
    tmdb_id: 1396,
    media_type: "tv",
    title: "Breaking Bad",
    overview: "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    release_date: "2008-01-20",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":80,"name":"Crime"}],
    status: "watched",
    rating: 3,
    favorite: true,
    added_at: ts(24),
    watched_at: ts(24),
  }),
  title({
    id: "demo-watched-3",
    tmdb_id: 136315,
    media_type: "tv",
    title: "The Bear",
    overview: "Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his chosen family.",
    poster_path: "/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg",
    backdrop_path: "/wHNwlE6ftEpgjVbdhLXOtv1hLs0.jpg",
    release_date: "2022-06-23",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":35,"name":"Comedy"}],
    status: "watched",
    rating: 3,
    review: "Stress incarnate. Carmy, Sydney, and Richie are a masterclass in character writing.",
    added_at: ts(25),
    watched_at: ts(25),
  }),
  title({
    id: "demo-watched-4",
    tmdb_id: 496243,
    media_type: "movie",
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    release_date: "2019-05-30",
    runtime: 133,
    genres: [{"id":35,"name":"Comedy"},{"id":53,"name":"Thriller"},{"id":18,"name":"Drama"}],
    status: "watched",
    rating: 3,
    favorite: true,
    added_at: ts(26),
    watched_at: ts(26),
  }),
  title({
    id: "demo-watched-5",
    tmdb_id: 67070,
    media_type: "tv",
    title: "Fleabag",
    overview: "A portrait into the mind of a dry-witted, sexual, angry, porn-watching, grief-riddled woman, trying to make sense of the world. As she hurls herself headlong at modern living, Fleabag is thrown roughly up against the walls of contemporary London, with all its frenetic energy, late nights, and bright lights.",
    poster_path: "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
    backdrop_path: "/hXdQ4MWsEOX6qg6VydKrLb3YJ4g.jpg",
    release_date: "2016-07-21",
    runtime: null,
    genres: [{"id":35,"name":"Comedy"},{"id":18,"name":"Drama"}],
    status: "watched",
    rating: 3,
    added_at: ts(27),
    watched_at: ts(27),
  }),
  title({
    id: "demo-watched-6",
    tmdb_id: 493922,
    media_type: "movie",
    title: "Hereditary",
    overview: "Following the death of the Leigh family matriarch, Annie and her children uncover disturbing secrets about their heritage. Their daily lives are not only impacted, but they also become entangled in a chilling fate from which they cannot escape, driving them to the brink of madness.",
    poster_path: "/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg",
    backdrop_path: "/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg",
    release_date: "2018-06-07",
    runtime: 128,
    genres: [{"id":27,"name":"Horror"},{"id":9648,"name":"Mystery"},{"id":53,"name":"Thriller"}],
    status: "watched",
    rating: 2,
    added_at: ts(28),
    watched_at: ts(28),
  }),
  title({
    id: "demo-watched-7",
    tmdb_id: 244786,
    media_type: "movie",
    title: "Whiplash",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_path: "/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg",
    release_date: "2014-10-10",
    runtime: 107,
    genres: [{"id":18,"name":"Drama"},{"id":10402,"name":"Music"},{"id":53,"name":"Thriller"}],
    status: "watched",
    rating: 3,
    review: "Not my tempo. A perfect film.",
    favorite: true,
    added_at: ts(29),
    watched_at: ts(29),
  }),
  title({
    id: "demo-watched-8",
    tmdb_id: 87739,
    media_type: "tv",
    title: "The Queen's Gambit",
    overview: "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.",
    poster_path: "/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
    backdrop_path: "/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg",
    release_date: "2020-10-23",
    runtime: null,
    genres: [{"id":18,"name":"Drama"}],
    status: "watched",
    rating: 2,
    added_at: ts(30),
    watched_at: ts(30),
  }),
  title({
    id: "demo-watched-9",
    tmdb_id: 376867,
    media_type: "movie",
    title: "Moonlight",
    overview: "The tender, heartbreaking story of a young man’s struggle to find himself, told across three defining chapters in his life as he experiences the ecstasy, pain, and beauty of falling in love, while grappling with his own sexuality.",
    poster_path: "/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    backdrop_path: "/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg",
    release_date: "2016-10-21",
    runtime: 111,
    genres: [{"id":18,"name":"Drama"}],
    status: "watched",
    rating: 3,
    added_at: ts(31),
    watched_at: ts(31),
  }),
  title({
    id: "demo-watched-10",
    tmdb_id: 1104,
    media_type: "tv",
    title: "Mad Men",
    overview: "Set in 1960-1970 New York, this sexy, stylized and provocative drama follows the lives of the ruthlessly competitive men and women of Madison Avenue advertising.",
    poster_path: "/7v8iCNzKFpdlrCMcqCoJyn74Nsa.jpg",
    backdrop_path: "/A5lVyejMsP5G7rAJBwU9ug3Wzou.jpg",
    release_date: "2007-07-19",
    runtime: null,
    genres: [{"id":18,"name":"Drama"}],
    status: "watched",
    rating: 3,
    added_at: ts(32),
    watched_at: ts(32),
  }),
  title({
    id: "demo-watched-11",
    tmdb_id: 313369,
    media_type: "movie",
    title: "La La Land",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop_path: "/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
    release_date: "2016-12-01",
    runtime: 129,
    genres: [{"id":35,"name":"Comedy"},{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],
    status: "watched",
    rating: 2,
    added_at: ts(33),
    watched_at: ts(33),
  }),
  title({
    id: "demo-watched-12",
    tmdb_id: 329865,
    media_type: "movie",
    title: "Arrival",
    overview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    poster_path: "/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    backdrop_path: "/uKPbFF08QkRMvIAsgCh1soeyPhZ.jpg",
    release_date: "2016-11-10",
    runtime: 116,
    genres: [{"id":18,"name":"Drama"},{"id":878,"name":"Science Fiction"},{"id":9648,"name":"Mystery"}],
    status: "watched",
    rating: 3,
    added_at: ts(34),
    watched_at: ts(34),
  }),
  title({
    id: "demo-watched-13",
    tmdb_id: 27205,
    media_type: "movie",
    title: "Inception",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    poster_path: "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    release_date: "2010-07-15",
    runtime: 148,
    genres: [{"id":28,"name":"Action"},{"id":878,"name":"Science Fiction"},{"id":12,"name":"Adventure"}],
    status: "watched",
    rating: 3,
    favorite: true,
    added_at: ts(35),
    watched_at: ts(35),
  }),
  title({
    id: "demo-watched-14",
    tmdb_id: 680,
    media_type: "movie",
    title: "Pulp Fiction",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    release_date: "1994-09-10",
    runtime: 154,
    genres: [{"id":53,"name":"Thriller"},{"id":80,"name":"Crime"},{"id":35,"name":"Comedy"}],
    status: "watched",
    rating: 3,
    review: "The dream logic holds up on every rewatch.",
    added_at: ts(36),
    watched_at: ts(36),
  }),
  title({
    id: "demo-watched-15",
    tmdb_id: 155,
    media_type: "movie",
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg",
    release_date: "2008-07-16",
    runtime: 152,
    genres: [{"id":28,"name":"Action"},{"id":80,"name":"Crime"},{"id":53,"name":"Thriller"}],
    status: "watched",
    rating: 3,
    favorite: true,
    added_at: ts(37),
    watched_at: ts(37),
  }),
  title({
    id: "demo-watched-16",
    tmdb_id: 299534,
    media_type: "movie",
    title: "Avengers: Endgame",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    poster_path: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    release_date: "2019-04-24",
    runtime: 181,
    genres: [{"id":12,"name":"Adventure"},{"id":878,"name":"Science Fiction"},{"id":28,"name":"Action"}],
    status: "watched",
    rating: 2,
    added_at: ts(38),
    watched_at: ts(38),
  }),

  // ── Dropped (4) ───────────────────────────────────────────────
  title({
    id: "demo-dropped-1",
    tmdb_id: 94997,
    media_type: "tv",
    title: "House of the Dragon",
    overview: "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    backdrop_path: "/2xGcSLyTAzConiHAByWqhfLiatT.jpg",
    release_date: "2022-08-21",
    runtime: null,
    genres: [{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":18,"name":"Drama"},{"id":10759,"name":"Action & Adventure"}],
    status: "dropped",
    added_at: ts(39),
    watched_at: null,
  }),
  title({
    id: "demo-dropped-2",
    tmdb_id: 71912,
    media_type: "tv",
    title: "The Witcher",
    overview: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    poster_path: "/AoGsDM02UVt0npBA8OvpDcZbaMi.jpg",
    backdrop_path: "/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    release_date: "2019-12-20",
    runtime: null,
    genres: [{"id":18,"name":"Drama"},{"id":10759,"name":"Action & Adventure"}],
    status: "dropped",
    added_at: ts(40),
    watched_at: null,
  }),
  title({
    id: "demo-dropped-3",
    tmdb_id: 63247,
    media_type: "tv",
    title: "Westworld",
    overview: "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
    poster_path: "/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
    backdrop_path: "/rX5hvSRB2k4YoIvRg6Zky52rWk0.jpg",
    release_date: "2016-10-02",
    runtime: null,
    genres: [{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":37,"name":"Western"}],
    status: "dropped",
    added_at: ts(41),
    watched_at: null,
  }),
  title({
    id: "demo-dropped-4",
    tmdb_id: 60625,
    media_type: "tv",
    title: "Rick and Morty",
    overview: "Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.",
    poster_path: "/WGRQ8FpjkDTzivQJ43t94bOuY0.jpg",
    backdrop_path: "/Ao5pBFuWY32cVuh6iYjEjZMEscN.jpg",
    release_date: "2013-12-02",
    runtime: null,
    genres: [{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":10765,"name":"Sci-Fi & Fantasy"},{"id":10759,"name":"Action & Adventure"}],
    status: "dropped",
    added_at: ts(42),
    watched_at: null,
  })
];

export const DEMO_LISTS: ListRow[] = [
  {
    id: "demo-list-1",
    slug: "cozy-winter",
    name: "Cozy winter",
    description: "Films and series that feel like a warm blanket when it's cold outside.",
    created_at: ts(42),
  },
  {
    id: "demo-list-2",
    slug: "a24-horror",
    name: "A24 horror",
    description: "Slow-burn, unsettling, beautifully shot.",
    created_at: ts(35),
  },
  {
    id: "demo-list-3",
    slug: "all-time-favorites",
    name: "All-time favorites",
    description: "The ones I'd rewatch any day.",
    created_at: ts(28),
  },
];

export interface DemoListTitle {
  list_id: string;
  title_id: string;
  position: number;
  added_at: string;
}

export const DEMO_LIST_TITLES: DemoListTitle[] = [
  // Cozy winter
  { list_id: "demo-list-1", title_id: "demo-watched-11", position: 0, added_at: ts(42) },
  { list_id: "demo-list-1", title_id: "demo-watched-5",  position: 1, added_at: ts(42) },
  { list_id: "demo-list-1", title_id: "demo-watched-9",  position: 2, added_at: ts(42) },
  { list_id: "demo-list-1", title_id: "demo-want-6",     position: 3, added_at: ts(42) },
  { list_id: "demo-list-1", title_id: "demo-watched-8",  position: 4, added_at: ts(42) },
  // A24 horror
  { list_id: "demo-list-2", title_id: "demo-watched-6",  position: 0, added_at: ts(35) },
  { list_id: "demo-list-2", title_id: "demo-want-3",     position: 1, added_at: ts(35) },
  { list_id: "demo-list-2", title_id: "demo-watched-4",  position: 2, added_at: ts(35) },
  { list_id: "demo-list-2", title_id: "demo-want-8",     position: 3, added_at: ts(35) },
  // All-time favorites
  { list_id: "demo-list-3", title_id: "demo-watched-1",  position: 0, added_at: ts(28) },
  { list_id: "demo-list-3", title_id: "demo-watched-2",  position: 1, added_at: ts(28) },
  { list_id: "demo-list-3", title_id: "demo-watched-4",  position: 2, added_at: ts(28) },
  { list_id: "demo-list-3", title_id: "demo-watched-7",  position: 3, added_at: ts(28) },
  { list_id: "demo-list-3", title_id: "demo-watched-13", position: 4, added_at: ts(28) },
  { list_id: "demo-list-3", title_id: "demo-watched-15", position: 5, added_at: ts(28) },
];
